blog/urls.py
from django.urls import path

from . import views
from .apps import BlogConfig
from .views import ArticleListView, ArticleCreateView, ArticleDeleteView, ArticleUpdateView, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('article/create/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<str:slug>/', ArticleDetailView.as_view(), name='article'),
    path('article/update/<int:pk>', ArticleUpdateView.as_view(), name='article_update'),
    path('article/delete/<int:pk>', ArticleDeleteView.as_view(), name='article_delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from catalog.models import NULLABLE


class Article(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержимое')
    slug = models.CharField(max_length=200, verbose_name='Слог')
    image = models.ImageField(upload_to='blog/', verbose_name='Изображение', **NULLABLE)
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        return f'{self.title} {self.views_count}'

    def get_absolute_url(self):
        return reverse('blog:article', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'
        ordering = ('-created_at',)
        permissions = [('set_published_status', 'Can publish article')]

blog/views.py
from django import forms
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from pytils.translit import slugify

from blog.models import Article
from utils.utils import send_greeting_email


class ArticleListView(ListView):
    model = Article
    extra_context = {
        'title': 'Dream shop - Blog',
        'sub_title': ''
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        # queryset = queryset.order_by('-created_at')
        return queryset


class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1  # Увеличиваем счетчик просмотров
        self.object.save()

        # Если количество просмотров статьи стало 100, то отправляем
        # поздравительное письмо
        if self.object.views_count == 100:
            send_greeting_email(self.object)

        return self.object

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title
        return context


class ArticleCreateView(CreateView):
    model = Article
    fields = ('title', 'content', 'image',)
    extra_context = {
        'title': 'Dream shop - Blog',
        'sub_title': 'Add article'
    }

    def get_success_url(self):
        return reverse('blog:article', args=[self.object.slug])

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            # slugify импортируем из pytils - поддержка русского языка - нужно установить
            new_article.slug = slugify(new_article.title)
            new_article.save()

        return super().form_valid(form)


class CanPublishArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content', 'image', 'is_published']


class CanNotPublishArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content', 'image']


class ArticleUpdateView(UpdateView):
    model = Article
    extra_context = {
        'title': 'Dream shop - Blog',
        'sub_title': 'Edit article'
    }

    def get_form_class(self):
        """Метод проверяет права пользователя. Если ему разрешено публиковать статьи,
        то выводим форму редактирования, включающую флажок Is_Published, иначе - флажок отсутствует.
        Но у пользователя в обоих случаях остается возможность редактировать статью"""
        if self.request.user.has_perm('blog.set_published_status'):
            return CanPublishArticleForm
        else:
            return CanNotPublishArticleForm

    def get_success_url(self):
        return reverse('blog:article', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['blog'] = get_object_or_404(Article, pk=self.kwargs.get('pk'))
        return context_data

    def form_valid(self, form):
        if form.is_valid():
            new_article = form.save()
            # slugify импортируем из pytils - поддержка русского языка - нужно установить
            new_article.slug = slugify(new_article.title)
            new_article.save()

        return super().form_valid(form)


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('blog:articles')

blog/templates/blog/article_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
    <form method="post" class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Удаление статьи
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    <p>Действительно хотите удалить статью:<br>"{{ object.title }}"?</p>
                    <button type="submit" class="btn btn-danger">Delete</button>
                    <a class="btn btn-outline-warning" href="{% url 'blog:articles' %}">Cancel</a>
                </div>

            </div>
        </div>
    </form>
{% endblock %}

blog/templates/blog/article_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container py-4">
    <div class="h-100 p-5 bg-body-tertiary border rounded-3">
        <div class="container-fluid py-5">
            <div class="text-body-secondary">
                <p>{{ object.created_at }}</p>
            </div>
            <p><small class="text-body-secondary">
                {{ object.views_count }} views
            </small></p>
            {% if object.image %}
            <img src="{{ object.image|mediapath }}" class="p-4 img-fluid"
                 width="650px" height="auto" alt="Responsive image">
            {% endif %}

            <p class="col-md-10 fs-4">{{ object.content|linebreaksbr }}</p>

            <div class="d-flex justify-content-between align-items-center">
                {% if user.is_authenticated %}
                <div class="btn-group">
                    <a class="btn btn-outline-secondary"
                       href="{% url 'blog:article_update' object.pk %}">Edit</a>
                    <a class="btn btn-outline-danger"
                       href="{% url 'blog:article_delete' object.pk %}">Delete</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/article_form.html
{% extends 'catalog/base.html' %}
{% block content %}
    <form method="post" class="row" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    {% if object %}
                        Edit article
                    {% else %}
                        Add article
                    {% endif %}
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-secondary">
                        {% if object %}
                            Save
                        {% else %}
                            Add
                        {% endif %}
                    </button>
<!--                    <button type="submit" class="btn btn-outline-secondary">-->
<!--                        Cancel-->
<!--                    </button>-->
                </div>
            </div>
        </div>
    </form>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

{% if user.is_authenticated %}
<div class="col-12 mb-5">
    <a class="btn btn-secondary" href="{% url 'blog:article_create' %}">Add article</a>
</div>
{% endif %}

{% for object in object_list %}

<div class="card h-100 mb-3">
<!--<div class="card mb-3" style="max-height: 600px;">-->
    <div class="row g-0">
        <div class="card-header">
            <p><h4 class="card-title">{{ object.title }}</h4></p>
        </div>
        {% if object.image %}
        <div class="col-md-4">
            <img src="{{ object.image|mediapath }}" class="img-fluid rounded-start" alt="Article image">
        </div>
        {% endif %}
        <div class="col-md-8">
            <div class="card-body">
                <small class="text-body-secondary">
                    <p>{{ object.created_at }}</p>
                </small>
                <p class="card-text">{{ object.content|truncatechars:200 }}</p>

            </div>
        </div>
        <div class="card-footer">
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group btn-group-sm">
                    <a class="btn btn-outline-secondary" href="{% url 'blog:article' object.slug %}">View</a>
<!--                    <a class="btn btn-outline-secondary" href="{{ object.get_absolute_url }}">View</a>-->
                    {% if user.is_authenticated %}
                        <a class="btn btn-outline-secondary" href="{% url 'blog:article_update' object.pk %}">Edit</a>
                        <a class="btn btn-outline-danger" href="{% url 'blog:article_delete' object.pk %}">Delete</a>
                    {% endif %}
                </div>
                <small class="text-body-secondary">{{ object.views_count }} views</small>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}