blog/urls.py
from django.urls import path

from . import views
from .apps import BlogConfig
from .views import ArticleListView, ArticleCreateView, ArticleDeleteView, ArticleUpdateView, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('article/create/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<str:slug>/', ArticleDetailView.as_view(), name='article'),
    path('article/update/<int:pk>', ArticleUpdateView.as_view(), name='article_update'),
    path('article/delete/<int:pk>', ArticleDeleteView.as_view(), name='article_delete'),

]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views
from .apps import CatalogConfig
from .views import CategoryListView, ProductListView, ProductDetailView, IndexView, ProductCreateView, \
    ProductUpdateView, ProductDeleteView, VersionUpdateView, VersionListView, VersionDeleteView, VersionCreateView

app_name = CatalogConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('category/<int:pk>/', ProductListView.as_view(), name='category'),

    path('categories/', CategoryListView.as_view(), name='categories'),

    path('product/<int:pk>/versions/', VersionListView.as_view(), name='version_list'),
    path('product/version/create/', VersionCreateView.as_view(), name='version_create'),
    path('product/version/<int:pk>/update/', VersionUpdateView.as_view(), name='version_update'),
    path('product/version/<int:pk>/delete/', VersionDeleteView.as_view(), name='version_delete'),

    path('contacts/', views.contacts, name='contacts'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, activate_user, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm/<str:token>', activate_user, name='confirm'),
    path('resetpassword/', reset_password, name='reset_password'),
]

catalog/models.py
from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Категория')
    description = models.TextField(verbose_name='Описание')
    # created_at = models.DateField(default=date.today, verbose_name='Дата создания')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='products/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.PositiveIntegerField(verbose_name='Цена')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    modified_date = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                                   verbose_name='Кем создан', **NULLABLE)

    def __str__(self):
        return f'{self.name}/{self.category} - {self.price}'

    @property
    def active_version(self):
        versions = self.version_set.select_related()
        for version in versions:
            if version.is_active:
                return version
        return None

    @property
    def last_version(self):
        version = self.version_set.select_related()
        if version:
            return version.last()
        else:
            return None

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('name',)


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    name = models.CharField(max_length=150, verbose_name='Наименование')
    num = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='Номер')
    is_active = models.BooleanField(default=True, verbose_name='Версия активна')

    def __str__(self):
        return f'{self.product} version {self.name} {self.num}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'
        ordering = ('-num',)

catalog/forms.py
from django import forms
from django.shortcuts import render

from catalog.models import Product, Version
from config.settings import WORDS_BLACK_LIST
from utils.utils import text_to_set_without_punctuation


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_active':
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        # fields = '__all__'
        exclude = ('created_by',)

    def clean(self):
        cleaned_data = super().clean()
        for field in ['name', 'description']:
            cleaned_field_data = cleaned_data.get(field)
            text = text_to_set_without_punctuation(cleaned_field_data)
            if text:
                common_words: set = text & WORDS_BLACK_LIST
            else:
                break
            if len(common_words) > 0:
                raise forms.ValidationError(f'Incorrect words used: {", ".join(common_words)}')
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

    def clean_is_active(self):
        is_active = self.cleaned_data['is_active']
        product = self.cleaned_data['product']
        # product = self.instance.product  # Получаем связанный продукт
        if is_active:
            # Проверяем, есть ли другие активные версии этого продукта
            active_versions_count = Version.objects.filter(product=product, is_active=True).exclude(
                id=self.instance.id).count()
            if active_versions_count > 0:
                raise forms.ValidationError('Уже есть активная версия этого продукта.')
        return is_active

catalog/views.py
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Category, Version
from catalog.services import get_categories_cache
from utils.json_saver import write_to_json_file


class IndexView(TemplateView):
    # template_name = 'catalog/index.html'
    template_name = 'catalog/product_list.html'
    extra_context = {
        'title': 'Easy shopping with Dream',
        'sub_title': 'Explore our gadgets catalog',
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Product.objects.all()[:6]
        return context_data


class CategoryListView(ListView):
    model = Category
    extra_context = {
        'title': 'Dream shop - Categories',
        'sub_title': ''
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = get_categories_cache()
        return context_data

class ProductListView(ListView):
    model = Product

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category_id=self.kwargs.get('pk'))
        if not self.request.user.is_staff:
            queryset = queryset.filter(created_by=self.request.user)
        return queryset

    # Переопределяем экстра-контекст, так как у нас подставляются динамические данные
    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data['category_pk'] = category_item.pk
        context_data['title'] = f'Category {category_item.name}'
        return context_data


class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        product_item = Product.objects.get(pk=self.kwargs.get('pk'))
        version_item = Version.objects.filter(product=self.kwargs.get('pk'))
        # Можно вернуть только последнюю версию
        # if version_item:
        #     version_item = version_item.last()
        context_data['product_pk'] = product_item.pk
        context_data['version_item'] = version_item
        context_data['title'] = f'{product_item.name}'

        return context_data


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    extra_context = {
        'title': 'Add product',
        'sub_title': ''
    }

    def get_success_url(self):
        return reverse('catalog:product', args=[self.object.pk])

    def form_valid(self, form):
        self.object = form.save()
        self.object.created_by = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)

        # Разрешаем редактировать продукт только его создателю.
        if self.object.created_by != self.request.user and not self.request.user.is_staff:
            raise Http404

        return self.object

    def get_success_url(self):
        return reverse('catalog:product', args=[self.object.pk])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)
        context_data['formset'] = formset

        product_item = Product.objects.get(pk=self.kwargs.get('pk'))
        context_data['product_pk'] = product_item.pk
        context_data['title'] = f'Edit - {product_item.name}'

        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:index')


class VersionListView(ListView):
    model = Version

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(product_id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        product_item = Product.objects.get(pk=self.kwargs.get('pk'))
        context_data['product_pk'] = product_item.pk
        context_data['title'] = f'{product_item.name}'
        context_data['sub_title'] = 'Version history'

        return context_data


class VersionUpdateView(UpdateView):
    model = Version
    form_class = VersionForm

    def get_success_url(self):
        return reverse('catalog:version_list', args=[self.object.product_id])


class VersionDeleteView(DeleteView):
    model = Version

    def get_success_url(self):
        return reverse('catalog:version_list', args=[self.object.product_id])


class VersionCreateView(CreateView):
    model = Version
    form_class = VersionForm

    def get_success_url(self):
        return reverse('catalog:version_list', args=[self.object.product_id])


def contacts(request):
    context = {
        'title': 'Our Contacts',
        'sub_title': ''
    }
    data = []
    if request.method == 'POST':
        data.append({'name': request.POST.get('name'),
                     'email': request.POST.get('email'),
                     'message': request.POST.get('message')})
        write_to_json_file('messages.json', data)
    return render(request, 'catalog/contacts.html', context)

catalog/templates/catalog/includes/inc_add_product.html
{% if user.is_authenticated %}
<div class="col-12 mb-3">
    <a class="btn btn-secondary" href="{% url 'catalog:product_create' %}">Add product</a>
</div>
{% endif %}

catalog/templates/catalog/includes/inc_header.html
{% load my_tags %}
<header class="p-3 mb-3 border-bottom text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="navbar-brand d-flex align-items-center">

                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-bag-heart" viewBox="0 0 20 20">
                  <path fill-rule="evenodd" d="M10.5 3.5a2.5 2.5 0 0 0-5 0V4h5v-.5Zm1 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0ZM14 14V5H2v9a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1ZM8 7.993c1.664-1.711 5.825 1.283 0 5.132-5.825-3.85-1.664-6.843 0-5.132Z"/>
                </svg>

                <h4><strong>Dream shop</strong></h4>
            </a>
            <ul class="nav col-12 col-lg-3 me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'catalog:categories' %}" class="nav-link px-2 text-white">Categories</a></li>
                <li><a href="{% url 'blog:articles' %}" class="nav-link px-2 text-white">Blog</a></li>
                <li><a href="{% url 'catalog:contacts' %}" class="nav-link px-2 text-white">Contacts</a></li>
            </ul>

<!--            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">-->
<!--                <input type="search" class="form-control" placeholder="Search..." aria-label="Search">-->
<!--            </form>-->

            <div class="dropdown text-end">
<!--                <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"-->
                <a href="#" class="d-flex align-items-center text-white text-decoration-none"
                   id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                {% if user.is_authenticated %}
                    <img src="{{ user.avatar|mediapath }}" alt="" width="32" height="32" class="rounded-circle me-4">
                    {{ user.email }}
                {% else %}
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                         class="bi bi-person-circle" viewBox="0 0 16 16">
                        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                        <path fill-rule="evenodd"
                              d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                    </svg>
                {% endif %}
                </a>

                <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
                    {% if user.is_authenticated %}
                        <li><a class="dropdown-item" href="#">Profile</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Sign out</a></li>
                    {% else %}
                        <li><a class="dropdown-item" href="{% url 'users:login' %}">Sign in</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'users:register' %}">Sign up</a></li>
                    {% endif %}
                </ul>

            </div>
        </div>
    </div>
</header>

catalog/templates/catalog/includes/inc_product.html
{% load my_tags %}
<div class="col">
    <div class="card h-100 shadow-sm">
        <p class="text-center">
            <img src="{{ object.image|mediapath }}" class="p-3 img-fluid" width="225px" height="auto"
                 alt="Responsive image">
        </p>
        <div class="card-header py-3">
            <h5 class="my-0 fw-normal text-truncate">{{ object.name }}</h5>
        </div>
        <div class="card-body">
            <p class="card-text">{{ object.description|truncatechars:100 }}</p>
            <!--            <p class="card-text">{{ object.description|slice:":100" }}</p>-->
        </div>
        <div class="card-footer" style="min-height: 2.5rem;">
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group btn-group-sm">
                    <a class="btn btn-outline-secondary"
                       href="{% url 'catalog:product' object.pk %}">View</a>
                    {% if perms.catalog.change_product %}
<!--                    if user.is_authenticated-->
                        <a class="btn btn-outline-secondary"
                           href="{% url 'catalog:product_update' object.pk %}">Edit</a>
                        <a class="btn btn-outline-danger"
                           href="{% url 'catalog:product_delete' object.pk %}">Delete</a>
                    {% endif %}
                </div>
                {% if object.active_version.num %}
                    <small class="text-body-secondary">Version {{ object.active_version.num|floatformat:"2u" }}</small>
                {% endif %}
            </div>
        </div>
    </div>
</div>