blog/urls.py
from django.urls import path

from . import views
from .apps import BlogConfig
from .views import ArticleListView, ArticleCreateView, ArticleDeleteView, ArticleUpdateView, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('article/create/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<str:slug>/', ArticleDetailView.as_view(), name='article'),
    path('article/update/<int:pk>', ArticleUpdateView.as_view(), name='article_update'),
    path('article/delete/<int:pk>', ArticleDeleteView.as_view(), name='article_delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, activate_user, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm/<str:token>', activate_user, name='confirm'),
    path('resetpassword/', reset_password, name='reset_password'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class User(AbstractUser):
    username = None  # удаляем поле username, так как авторизовать будем по полю email
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    is_active = models.BooleanField(default=False, verbose_name='активирован')
    verification_token = models.CharField(max_length=50, **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

users/views.py
import random
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.utils.crypto import get_random_string
from django.views.generic import CreateView

from users.forms import UserRegisterForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm  # Переопределяем стандартную форму UserCreationForm на свою
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        self.object = form.save()
        self.object.verification_token = get_random_string(30)
        send_mail(
            subject='Activate Your Account Now',
            message=f'Hello!\nPlease, click link below to confirm your email\n'
                    f'http://{get_current_site(self.request)}/users/confirm/{self.object.verification_token}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.object.email]
        )
        return super().form_valid(form)


def activate_user(request, token):
    user = User.objects.get(verification_token=token)
    user.verification_token = ''
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


def reset_password(request):
    context = {
        'title': 'Resetting Password',
        'sub_title': 'You will receive a new password to the specified email'
    }

    if request.method == 'POST':
        # Проверка на существование введенного email в БД
        try:
            user = User.objects.get(email=request.POST.get('email'))
        except User.DoesNotExist:
            context = {
                'title': 'User with this email does not exist',
                'sub_title': 'Try entering the email again'
            }
            return render(request, 'users/pass_reset.html', context)
        # Генерируем пароль из 12-ти случайных цифр
        new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
        # Отправляем пароль по email пользователю
        send_mail(
            subject='New password',
            message=f'Hello!\nThis is your new password: {new_password}\n\nDo not tell it to anyone.',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        # Записываем в БД новый пароль
        user.set_password(new_password)
        user.save()
        # После отправки письма с паролем переходим на страницу авторизации
        return redirect(reverse_lazy('users:login'))
    return render(request, 'users/pass_reset.html', context)

users/templates/users/login.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <form method="post" class="row" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Sign in
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-secondary">
                        Sign in
                    </button>
                    <a class="btn btn-outline-secondary" onclick="history.back();">Cancel</a>
                </div>
                <div class="card-footer">
                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'users:reset_password' %}">Forgot password?</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/pass_reset.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-12">
    <form method="post" class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Enter your email address
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    <div class="mb-3">
                        <input name="email" type="email" class="form-control" id="exampleInputEmail1"
                               aria-describedby="emailHelp" placeholder="Email">
                    </div>
                    <button type="submit" class="btn btn-secondary">
                        Reset Password
                    </button>
                    <a class="btn btn-outline-secondary" onclick="history.back();">Cancel</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <form method="post" class="row" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Sign up
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-secondary">
                        Sign up
                    </button>
                    <a class="btn btn-outline-secondary" onclick="history.back();">Cancel</a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}