blog/urls.py
from django.urls import path

from . import views
from .apps import BlogConfig
from .views import ArticleListView, ArticleCreateView, ArticleDeleteView, ArticleUpdateView, ArticleDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('article/create/', ArticleCreateView.as_view(), name='article_create'),
    path('article/<str:slug>/', ArticleDetailView.as_view(), name='article'),
    path('article/update/<int:pk>', ArticleUpdateView.as_view(), name='article_update'),
    path('article/delete/<int:pk>', ArticleDeleteView.as_view(), name='article_delete'),

]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views
from .apps import CatalogConfig
from .views import CategoryListView, ProductListView, ProductDetailView, IndexView, ProductCreateView, \
    ProductUpdateView, ProductDeleteView, VersionUpdateView, VersionListView, VersionDeleteView, VersionCreateView

app_name = CatalogConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('category/<int:pk>/', ProductListView.as_view(), name='category'),

    path('categories/', CategoryListView.as_view(), name='categories'),

    path('product/<int:pk>/versions/', VersionListView.as_view(), name='version_list'),
    path('product/version/create/', VersionCreateView.as_view(), name='version_create'),
    path('product/version/<int:pk>/update/', VersionUpdateView.as_view(), name='version_update'),
    path('product/version/<int:pk>/delete/', VersionDeleteView.as_view(), name='version_delete'),

    path('contacts/', views.contacts, name='contacts'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Категория')
    description = models.TextField(verbose_name='Описание')
    # created_at = models.DateField(default=date.today, verbose_name='Дата создания')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='products/', verbose_name='Изображение', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.PositiveIntegerField(verbose_name='Цена')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    modified_date = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                                   verbose_name='Кем создан', **NULLABLE)

    def __str__(self):
        return f'{self.name}/{self.category} - {self.price}'

    @property
    def active_version(self):
        versions = self.version_set.select_related()
        for version in versions:
            if version.is_active:
                return version
        return None

    @property
    def last_version(self):
        version = self.version_set.select_related()
        if version:
            return version.last()
        else:
            return None

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ('name',)


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    name = models.CharField(max_length=150, verbose_name='Наименование')
    num = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='Номер')
    is_active = models.BooleanField(default=True, verbose_name='Версия активна')

    def __str__(self):
        return f'{self.product} version {self.name} {self.num}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'
        ordering = ('-num',)

catalog/forms.py
from django import forms
from django.shortcuts import render

from catalog.models import Product, Version
from config.settings import WORDS_BLACK_LIST
from utils.utils import text_to_set_without_punctuation


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_active':
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        # fields = '__all__'
        exclude = ('created_by',)

    def clean(self):
        cleaned_data = super().clean()
        for field in ['name', 'description']:
            cleaned_field_data = cleaned_data.get(field)
            text = text_to_set_without_punctuation(cleaned_field_data)
            if text:
                common_words: set = text & WORDS_BLACK_LIST
            else:
                break
            if len(common_words) > 0:
                raise forms.ValidationError(f'Incorrect words used: {", ".join(common_words)}')
        return cleaned_data


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

    def clean_is_active(self):
        is_active = self.cleaned_data['is_active']
        product = self.cleaned_data['product']
        # product = self.instance.product  # Получаем связанный продукт
        if is_active:
            # Проверяем, есть ли другие активные версии этого продукта
            active_versions_count = Version.objects.filter(product=product, is_active=True).exclude(
                id=self.instance.id).count()
            if active_versions_count > 0:
                raise forms.ValidationError('Уже есть активная версия этого продукта.')
        return is_active

catalog/views.py
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm
from catalog.models import Product, Category, Version
from catalog.services import get_categories_cache
from utils.json_saver import write_to_json_file


class IndexView(TemplateView):
    # template_name = 'catalog/index.html'
    template_name = 'catalog/product_list.html'
    extra_context = {
        'title': 'Easy shopping with Dream',
        'sub_title': 'Explore our gadgets catalog',
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Product.objects.all()[:6]
        return context_data


class CategoryListView(ListView):
    model = Category
    extra_context = {
        'title': 'Dream shop - Categories',
        'sub_title': ''
    }

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = get_categories_cache()
        return context_data

class ProductListView(ListView):
    model = Product

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category_id=self.kwargs.get('pk'))
        if not self.request.user.is_staff:
            queryset = queryset.filter(created_by=self.request.user)
        return queryset

    # Переопределяем экстра-контекст, так как у нас подставляются динамические данные
    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data['category_pk'] = category_item.pk
        context_data['title'] = f'Category {category_item.name}'
        return context_data


class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        product_item = Product.objects.get(pk=self.kwargs.get('pk'))
        version_item = Version.objects.filter(product=self.kwargs.get('pk'))
        # Можно вернуть только последнюю версию
        # if version_item:
        #     version_item = version_item.last()
        context_data['product_pk'] = product_item.pk
        context_data['version_item'] = version_item
        context_data['title'] = f'{product_item.name}'

        return context_data


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    extra_context = {
        'title': 'Add product',
        'sub_title': ''
    }

    def get_success_url(self):
        return reverse('catalog:product', args=[self.object.pk])

    def form_valid(self, form):
        self.object = form.save()
        self.object.created_by = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)

        # Разрешаем редактировать продукт только его создателю.
        if self.object.created_by != self.request.user and not self.request.user.is_staff:
            raise Http404

        return self.object

    def get_success_url(self):
        return reverse('catalog:product', args=[self.object.pk])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)
        context_data['formset'] = formset

        product_item = Product.objects.get(pk=self.kwargs.get('pk'))
        context_data['product_pk'] = product_item.pk
        context_data['title'] = f'Edit - {product_item.name}'

        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:index')


class VersionListView(ListView):
    model = Version

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(product_id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        product_item = Product.objects.get(pk=self.kwargs.get('pk'))
        context_data['product_pk'] = product_item.pk
        context_data['title'] = f'{product_item.name}'
        context_data['sub_title'] = 'Version history'

        return context_data


class VersionUpdateView(UpdateView):
    model = Version
    form_class = VersionForm

    def get_success_url(self):
        return reverse('catalog:version_list', args=[self.object.product_id])


class VersionDeleteView(DeleteView):
    model = Version

    def get_success_url(self):
        return reverse('catalog:version_list', args=[self.object.product_id])


class VersionCreateView(CreateView):
    model = Version
    form_class = VersionForm

    def get_success_url(self):
        return reverse('catalog:version_list', args=[self.object.product_id])


def contacts(request):
    context = {
        'title': 'Our Contacts',
        'sub_title': ''
    }
    data = []
    if request.method == 'POST':
        data.append({'name': request.POST.get('name'),
                     'email': request.POST.get('email'),
                     'message': request.POST.get('message')})
        write_to_json_file('messages.json', data)
    return render(request, 'catalog/contacts.html', context)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dream shop</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>


</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-outline-secondary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>

{% include 'catalog/includes/inc_header.html' %}

<main>

    <section class="py-2 text-center container">
        <div class="row py-lg-0">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">{{ title }}</h1>
                <p class="lead text-body-secondary">{{ sub_title }}</p>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">

            {% block content %}
            {% endblock %}

        </div>
    </div>

</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#" class="link text-secondary">Back to top</a>
        </p>
        <p class="mb-1">E-shop example is &copy; {% now ‘Y’ %} YA</p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block content %}
{% include 'catalog/includes/inc_add_product.html' %}

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for object in object_list %}

    <div class="col">
        <div class="card h-100 shadow-sm">
            <p class="text-center">
                <img src="/static/images/{{ object.name }}.jpeg" class="p-3 img-fluid" width="225px" height="auto"
                     alt="Responsive image">
            </p>
            <div class="card-body">
                <h2 class="card-title pricing-card-title">{{ object.name }}</h2>
                <p class="card-text">{{ object.description }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'catalog:category' object.pk %}" type="button"
                           class="btn btn-md btn-outline-secondary">View</a>
                        <!--                    <button type="button" class="btn btn-md btn-outline-secondary">Edit</button>-->
                        <!--                    <button type="button" class="btn btn-md btn-outline-danger">Delete</button>-->
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <main class="row mt-3">
        <div class="row">
            <div class="col-6">
                <div class="card bg-secondary">
                    <div class="card-body text-white">
                        <h3 class="card-header p-6 pb-md-4 mx-auto text-center">Our contacts</h3>
                        <div class="row mt-3">
                            <div class="col-3">Address</div>
                            <div class="col-9">One Apple Park Way<br>Cupertino, CA 95014
                            </div>
                            <div class="col-3">Phones</div>
                            <div class="col-9">+1-800–692–7753</div>
                            <div class="col-3"></div>
                            <div class="col-9">+1-408-996–1010</div>
                            <div class="col-3">E-mail</div>
                            <div class="col-9">info@apple.com</div>
                        </div>
                    </div>
                </div>
            </div>


            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-header p-6 pb-md-4 mx-auto text-center">Wright to us</h3>
                        <div class="row mt-3">
                            <form method="post">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <input name="name" type="text" class="form-control" id="exampleInputName"
                                           aria-describedby="nameHelp" placeholder="Name">
                                </div>
                                <div class="mb-3">
                                    <input name="email" type="email" class="form-control" id="exampleInputEmail1"
                                           aria-describedby="emailHelp" placeholder="Email">
                                </div>
                                <div class="mb-3">
                                    <textarea name="message" class="form-control" id="exampleFormControlTextarea1"
                                              placeholder="Message" rows="3"></textarea>
                                </div>

                                <button type="submit" class="btn btn-secondary form-control">Send</button>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}

{% block content %}
{% include 'catalog/includes/inc_add_product.html' %}

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for object in object_list %}
        {% include 'catalog/includes/inc_product.html' %}
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container py-4">

    <div class="h-100 p-5 bg-body-tertiary border rounded-3">
        <div class="container-fluid py-5">
            <img src="{{ object.image|mediapath }}" class="p-4 img-fluid"
                 width="400px" height="auto" alt="Responsive image">
            <h2 class="display-6">${{ object.price }}</h2>
            <p class="col-md-8 fs-4">{{ object.description }}</p>
            <button class="btn btn-primary btn-lg" type="button">Buy</button>
        </div>

    </div>

</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container py-4">
    <div class="h-100 p-5 bg-body-tertiary border rounded-3">
        <div class="container-fluid py-5">
            <img src="{{ object.image|mediapath }}" class="p-4 img-fluid"
                 width="400px" height="auto" alt="Responsive image">

            <h2 class="display-6">${{ object.price }}</h2><br>
            <p class="col-md-10 fs-4 mb-5">{{ object.description|linebreaksbr }}</p>

            <div class="d-flex justify-content-between align-items-top">
                <div class="col-6">
                    {% if user.is_authenticated %}
                    <div class="btn-group mb-3">
                        <!--                    <a class="btn btn-outline-secondary" onclick="history.back();">Back</a>-->
                        <a class="btn btn-outline-secondary"
                           href="{% url 'catalog:product_update' object.pk %}">Edit</a>
                        <a class="btn btn-outline-danger" href="{% url 'catalog:product_delete' object.pk %}">Delete</a>
                    </div>
                    {% endif %}
                </div>
                <div class="col-6">
                    <strong class="text-body-secondary">Versions history:</strong>
                    <small class="text-body-secondary">
                        {% for version in version_item %}
                            <br>
                            {{ version.num|floatformat:"2u" }}
                            {% if version.is_active %}
                                (active version)
                            {% endif %}
                        {% endfor %}
                    </small><br>
                    {% if user.is_authenticated %}
                        <div class="btn-group py-3">
                            <a class="btn btn-sm btn-outline-secondary" href="{% url 'catalog:version_list' object.pk %}">
                                Manage versions</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}
{% include 'catalog/includes/inc_add_product.html' %}

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for object in object_list %}
        {% include 'catalog/includes/inc_product.html' %}
    {% endfor %}
</div>

{% endblock %}

catalog/templates/catalog/version_list.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="row">
    <div class="col-2"></div>
    <div class="col-8">
        <div class="btn-toolbar mb-2 mb-md-3">
            <a type="button" class="btn btn-sm btn-secondary"
               href="{% url 'catalog:version_create'%}">Add new</a>
        </div>

        <div class="table-responsive small">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Number</th>
                    <th>Is active</th>
                    <th></th>
                </tr>
                </thead>

                {% for object in object_list %}
                <tr>
                    <td>{{ object.name }}</td>
                    <td>{{ object.num|floatformat:"2u" }}</td>
                    <td>
                        {% if object.is_active %}
                        <span class="badge rounded-pill text-bg-secondary">✓</span>
                        {% endif %}
                    </td>
                    <td>
                        <div class="d-grid gap-3 d-md-flex justify-content-md-end">
                            <a type="button" class="btn" href="{% url 'catalog:version_update' object.pk %}"
                               style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">
                                Edit
                            </a>
                            <a type="button" class="btn" href="{% url 'catalog:version_delete' object.pk %}"
                               style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">
                                Delete
                            </a>

                        </div>
                    </td>
                </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>
{% endblock %}